#!/usr/bin/env bash
# -*- mode: shell-script; sh-shell: bash; sh-basic-offset: 4; sh-indentation: 4; coding: utf-8 -*-
# shellcheck shell=bash

set -o nounset -o errexit -o errtrace -o pipefail

project.load_task_library "shell"

# shellcheck disable=SC2154
readonly MYCMD_DIR="${MYPROJECT_BASE_DIR}/mycmd"
# shellcheck disable=SC2154
readonly BOOTSTRAP_DIR="${MYPROJECT_BASE_DIR}/bootstrap"
# shellcheck disable=SC2154
readonly TEMPLATE_DIR="${MYPROJECT_BASE_DIR}/.chezmoitemplates"

project.register_fileset ALL_BASH_SCRIPTS
project.find_files_for_fileset ALL_BASH_SCRIPTS "${MYCMD_DIR}" -type f
project.find_files_for_fileset ALL_BASH_SCRIPTS "${BOOTSTRAP_DIR}" -type f
# shellcheck disable=SC2154
project.add_files_to_fileset ALL_BASH_SCRIPTS "${MYPROJECT_PROJECT_FILE}"

project.register_task_with_fileset list-all-bash-scripts project.list-files ALL_BASH_SCRIPTS
project.register_task_with_fileset format-all-bash-scripts project:shell.format ALL_BASH_SCRIPTS
project.register_task_with_fileset lint-all-bash-scripts project:shell.lint ALL_BASH_SCRIPTS

project.register_fileset ALL_COMMAND_GROUPS
project.find_files_for_fileset ALL_COMMAND_GROUPS "${MYCMD_DIR}" -name "*-lib" -type f
project.register_task_with_fileset list-all-command-groups project.list-files ALL_COMMAND_GROUPS

project.register_fileset ALL_COMMANDS
project.find_files_for_fileset ALL_COMMANDS "${MYCMD_DIR}" -type f ! -name "*-lib"
project.register_task_with_fileset list-all-commands project.list-files ALL_COMMANDS

mycmd.defer_at_startup mycmd.init_bin chezmoi

function diff-packages-toml() {
    # This is in this function so this doesn't prevent the project file from
    # loading on non-Mac OS platforms.
    mycmd.init_bin brew

    # shellcheck disable=SC2312
    diff <(mycmd.bin_execute brew bundle dump --force --file=- 2>/dev/null | sort -u) \
         <(mycmd.bin_execute chezmoi execute-template <"${TEMPLATE_DIR}/Brewfile" | sort -u)
}
project.register_task diff-packages-toml
