#!/usr/bin/env bash
# -*- mode: shell-script; sh-shell: bash; sh-basic-offset: 4; sh-indentation: 4; coding: utf-8 -*-
# shellcheck shell=bash

set -o nounset -o errexit -o errtrace -o pipefail

project.load_task_library "shell"

# shellcheck disable=SC2154
readonly MYCMD_DIR="${MYPROJECT_BASE_DIR}/mycmd"

project.register_fileset ALL_BASH_SCRIPTS
project.find_files_for_fileset ALL_BASH_SCRIPTS "${MYCMD_DIR}" -type f
# shellcheck disable=SC2154
project.add_files_to_fileset ALL_BASH_SCRIPTS "${MYPROJECT_PROJECT_FILE}"

project.register_task_with_fileset list-all-bash-scripts project.list-files ALL_BASH_SCRIPTS
project.register_task_with_fileset format-all-bash-scripts shell.format ALL_BASH_SCRIPTS
project.register_task_with_fileset lint-all-bash-scripts shell.lint ALL_BASH_SCRIPTS

project.register_fileset ALL_COMMAND_GROUPS
project.find_files_for_fileset ALL_COMMAND_GROUPS "${MYCMD_DIR}" -name "*-lib" -type f
project.register_task_with_fileset list-all-command-groups project.list-files ALL_COMMAND_GROUPS

project.register_fileset ALL_COMMANDS
project.find_files_for_fileset ALL_COMMANDS "${MYCMD_DIR}" -type f ! -name "*-lib"
project.register_task_with_fileset list-all-commands project.list-files ALL_COMMANDS
