#!/usr/bin/env bash
# shellcheck shell=bash

set -o nounset -o errexit -o errtrace -o pipefail

[ -z "${MYCMD_SYSTEM_BASE_DIR-}" ] && {
    echo >&2 "The script $0 should only be launched using 'mycmd'."
    exit 1
}

# shellcheck source=../../mycmd-lib
source "${MYCMD_SYSTEM_BASE_DIR}/mycmd-lib"
mycmd.auto_source_mycmd_libs

mycmd.source_mycmd_lib "financial/data-cleaning"

function main() {
    local date="$1"

    data_cleaning.clean_capitalone_checking_csv "${date}"

    import.import_capital_one_checking_cleaned_by_date "${date}"
}

main "$@"
