#!/usr/bin/env bash
# shellcheck shell=bash

set -o nounset -o errexit -o errtrace -o pipefail

[ -z "${MYCMD_SYSTEM_BASE_DIR-}" ] && {
    echo >&2 "The script $0 should only be launched using 'mycmd'."
    exit 1
}

# shellcheck source=../../mycmd-lib
source "${MYCMD_SYSTEM_BASE_DIR}/mycmd-lib"
mycmd.auto_source_mycmd_libs

function main() {
    local date="$1"

    data_cleaning.clean_capitalone_money_market_csv "${date}"
}

main "$@"
