#!/usr/bin/env bash
# shellcheck shell=bash

set -o nounset -o errexit -o errtrace -o pipefail

[ -z "${MYCMD_BASE_DIR-}" ] && {
    echo >&2 "The script $0 should only be launched using 'mycmd'."
    exit 1
}

# shellcheck source=../../mycmd-lib
source "${MYCMD_BASE_DIR}/mycmd-lib"
mycmd.auto_source_mycmd_libs

function main() {
    if (( $# < 1 )); then
        mycmd.trace "Listing all CSVs"

        financial.list_chase_visa_source_csvs_by_date
        financial.list_capital_one_money_market_source_csvs_by_date
        financial.list_capital_one_checking_source_csvs_by_date
    fi
}

main "$@"
