[packages]

[packages.darwin]
taps = [
  "daviderestivo/emacs-head",
  "homebrew/bundle",
  "homebrew/cask-fonts",
  "homebrew/cask-versions",
  "saulpw/vd"
]
brews = [
  "aspell",
  "bash",
  "bash-language-server",
  "bat",
  "bat-extras",
  "chezmoi",
  "coreutils",
  "diffoscope",
  "direnv",
  "exercism",
  "eza",
  "fd",
  "findutils",
  "fzf",
  "gawk",
  "gh",
  "git",
  "go",
  "go-critic",
  "golangci-lint",
  "graphviz",
  "grep",
  "grip",
  "gum",
  "hatch",
  "hyperfine",
  "ispell",
  "jless",
  "jq",
  "ledger",
  "mas",
  "mise",
  "moreutils",
  "pandoc",
  "pipx",
  "poetry",
  "poppler",
  "qemu",
  "rename",
  "ripgrep",
  "rustup-init",
  "saulpw/vd/visidata",
  "shellcheck",
  "shfmt",
  "symlinks",
  "tmux",
  "tree-sitter",
  "wordnet",
  "xsv",
  "yj",
  "zellij"
]
casks = [
  "cleanmymac",
  "discord",
  "epic-games",
  "foxit-pdf-editor",
  "font-commit-mono",
  "font-meslo-for-powerlevel10k",
  "font-monaspace",
  "font-monaspace-nerd-font",
  "font-sauce-code-pro-nerd-font",
  "font-source-code-pro",
  "font-symbols-only-nerd-font",
  "google-chrome",
  "google-drive",
  "iterm2",
  "jetbrains-toolbox",
  "karabiner-elements",
  "keybase",
  "keyclu",
  "loupedeck",
  "mysides",
  "raycast",
  "signal",
  "spotify",
  "steam",
  "tabula",
  "visual-studio-code-insiders",
  "vivaldi",
  "webcatalog",
  "zed",
  "zoom"
]

[[packages.darwin.brews_with_args]]
args = [
  "with-cocoa",
  "with-imagemagick",
  "with-modern-icon-bokehlicia-captiva",
  "with-native-comp",
  "with-native-full-aot",
  "with-tree-sitter"
]
name = "daviderestivo/emacs-head/emacs-head@29"

[[packages.darwin.brews_with_args]]
args = ["HEAD"]
name = "neovim"

[[packages.darwin.mas]]
id = 937984704
name = "Amphetamine"

[[packages.darwin.mas]]
id = 1352778147
name = "Bitwarden"

[[packages.darwin.mas]]
id = 6444915884
name = "Ice Cubes"

[[packages.darwin.mas]]
id = 302584613
name = "Kindle"

[[packages.darwin.mas]]
id = 803453959
name = "Slack"

[[packages.darwin.mas]]
id = 1607635845
name = "Velja"

[[packages.darwin.mas]]
id = 497799835
name = "Xcode"

[[packages.darwin.mas]]
id = 6451135429
name = "EnergizeLab"
