[packages]

[packages.darwin]
taps = [
  "daviderestivo/emacs-head",
  "dbcli/tap",
  "homebrew/bundle",
  "homebrew/cask-fonts",
  "homebrew/cask-versions",
  "homebrew/services",
  "saulpw/vd"
]
brews = [
  "aspell",
  "bash",
  "bash-language-server",
  "bat",
  "bat-extras",
  "beautysh",
  "black",
  "chezmoi",
  "coreutils",
  "dbcli/tap/litecli",
  "diffoscope",
  "direnv",
  "duckdb",
  "exercism",
  "exiftool",
  "eza",
  "fd",
  "ffmpegthumbnailer",
  "findutils",
  "flamegraph",
  "fzf",
  "gawk",
  "gh",
  "git",
  "git-quick-stats",
  "gmailctl",
  "go",
  "go-critic",
  "golangci-lint",
  "gpg",
  "graphviz",
  "grep",
  "grip",
  "gum",
  "gyb",
  "hatch",
  "htmlq",
  "hyperfine",
  "imagemagick",
  "isort",
  "ispell",
  "janet",
  "jless",
  "jq",
  "ledger",
  "links",
  "mas",
  "media-info",
  "mise",
  "moreutils",
  "neovim",
  "ninja",
  "oils-for-unix",
  "pandoc",
  "pipx",
  "pkgconf",
  "poetry",
  "poppler",
  "qemu",
  "rename",
  "ripgrep",
  "rustup",
  "saulpw/vd/visidata",
  "shellcheck",
  "shfmt",
  "sleek",
  "symlinks",
  "tmux",
  "tree-sitter",
  "wget",
  "wordnet",
  "xsv",
  "yj",
  "yt-dlp",
  "zellij",
  "zig"
]
casks = [
  "cleanmymac",
  "discord",
  "epic-games",
  "foxit-pdf-editor",
  "font-commit-mono",
  "font-meslo-for-powerlevel10k",
  "font-monaspace",
  "font-monaspace-nerd-font",
  "font-sauce-code-pro-nerd-font",
  "font-source-code-pro",
  "font-symbols-only-nerd-font",
  "ghostty",
  "google-chrome",
  "google-drive",
  "iterm2",
  "jetbrains-toolbox",
  "karabiner-elements",
  "keybase",
  "keyclu",
  "loupedeck",
  "mysides",
  "openmtp",
  "raycast",
  "signal",
  "spotify",
  "steam",
  "tabula",
  "visual-studio-code@insiders",
  "vivaldi",
  "vlc",
  "webcatalog",
  "zed",
  "zoom"
]

[[packages.darwin.brews_with_args]]
args = [
  "with-cocoa",
  "with-imagemagick",
  "with-modern-icon-bokehlicia-captiva",
  "with-native-comp",
  "with-native-full-aot",
  "with-poll",
  "with-tree-sitter"
]
name = "daviderestivo/emacs-head/emacs-head@30"

[[packages.darwin.brews_with_args]]
args = ["HEAD"]
name = "utf8proc"

[[packages.darwin.mas]]
id = 937984704
name = "Amphetamine"

[[packages.darwin.mas]]
id = 1352778147
name = "Bitwarden"

[[packages.darwin.mas]]
id = 6444915884
name = "Ice Cubes"

[[packages.darwin.mas]]
id = 302584613
name = "Kindle"

[[packages.darwin.mas]]
id = 803453959
name = "Slack"

[[packages.darwin.mas]]
id = 1607635845
name = "Velja"

[[packages.darwin.mas]]
id = 497799835
name = "Xcode"

[[packages.darwin.mas]]
id = 6451135429
name = "EnergizeLab"

[[packages.darwin.mas]]
id = 1494992020
name = "Supernote Partner"

[packages.linux]
debs = [
  "aspell",
  "aspell-en",
  "bat",
  "emacs-pgtk",
  "fd-find",
  "fzf",
  "ispell",
  "jq",
  "ledger",
  "ripgrep",
  "tree-sitter",
  "tmux",
  "visidata",
  "zsh"
]
